### ISSUE TITLE
Exception thrown when importing playlist

### ISSUE THREAD

**Issue by karrakoliko** [lemonpaul/yandex2spotify#11]
```2020-07-20 16:43:25,150 - INFO - Importing playlist ANIIML - SLAY! (2018)...
2020-07-20 16:43:28,983 - WARNING - Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
2020-07-20 16:43:28,987 - WARNING - Type: <class 'yandex_music.track.meta_data.MetaData'>; kwargs: {'version': 'Visit http://aniimlmusic.bandcamp.com'}
2020-07-20 16:43:28,992 - INFO - Importing track: ANIIML - SLAY!...
2020-07-20 16:43:29,191 - INFO - OK
2020-07-20 16:43:29,191 - INFO - Saving 1 tracks in playlist ANIIML - SLAY! (2018)...
2020-07-20 16:43:29,407 - INFO - OK
2020-07-20 16:43:29,641 - INFO - Importing playlist LEViT∆TE - Fatalism EP (2019)...
Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "importer.py", line 233, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore).import_all()
  File "importer.py", line 190, in import_all
    item()
  File "importer.py", line 144, in import_playlists
    self.spotify_client.playlist_upload_cover_image(spotify_playlist_id, encode_file_base64(filename_jpg))
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 553, in playlist_upload_cover_image
    content_type="image/jpeg",
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 225, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 172, in _internal_call
    timeout=self.requests_timeout, **args
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))```

**Comment by MarshalX** [comment]
The same playlist as in the library issue?

**Comment by karrakoliko** [comment]
> 
> 
> The same playlist as in the library issue?

yes https://clck.ru/PmPAw
This playlist contain uploaded file (YM library doesn't contain this track). May be this info will be useful ;)

**Comment by karrakoliko** [comment]
OR may be this one (I'm not sure): https://bit.ly/2E0yNuQ
Both playlists have uploaded tracks

**Comment by MarshalX** [comment]
Do playlists have custom covers or from tracks?

**Comment by karrakoliko** [comment]
> 
> 
> Do playlists have custom covers or from tracks?

custom

**Comment by MarshalX** [comment]
@glebliutsko cover download link is available. Size 1000x1000 exists

**Comment by MarshalX** [comment]
![image](https://user-images.githubusercontent.com/15520314/87911053-a8c8c080-ca73-11ea-95ce-9707823061a2.png)

![image](https://user-images.githubusercontent.com/15520314/87910987-8e8ee280-ca73-11ea-801d-f92fc1c4ea4e.png)
@glebliutsko  what's the move?

**Comment by MarshalX** [comment]
@vtuu can you check on another branch?
