### ISSUE TITLE
api.spotify.com read timed out. 

### ISSUE THREAD

**Issue by AxelRUS** [lemonpaul/yandex2spotify#15]
Вышло при импорте какого-то из плейлистов...

```
2020-07-21 14:26:57,418 - INFO - Importing track: Limp Bizkit - Break Stuff...
Traceback (most recent call last):
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1332, in getresponse
    response.begin()
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\urllib3\connectionpool.py", line 330, in _raise_timeourllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\importer.py", line 228, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore).import_all()
  File ".\importer.py", line 185, in import_all
    item()
  File ".\importer.py", line 153, in import_playlists
    self._add_items_to_spotify(tracks, self.not_imported[playlist.title], save_tracks_callback, Type.TRACK)
  File ".\importer.py", line 101, in _add_items_to_spotify
    found_items = self.spotify_client.search(item_name, type=type_.value)[f'{type_.value}s']['items']
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\spotipy\client.py", line 463, in search
    return self._get(
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\spotipy\client.py", line 210, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\spotipy\client.py", line 170, in _internal_call
    response = self._session.request(
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Axel\Desktop\yandex2spotify\env\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)
(env) PS C:\Users\Axel\Desktop\yandex2spotify>
```

**Comment by lemonpaul** [comment]
Странно, запрос прервался при поиске трека. Возможно связано с [предыдущим issue](https://github.com/lemonpaul/yandex2spotify/issues/16). Проверь, пожалуйста, если не сложно.

**Comment by AxelRUS** [comment]
Нет, запустил повторно импорт на той же ревизии - он прошел.
Можно попробовать добавить несколько попыток, например 3, если спотифай апи не отвечает.

**Comment by MarshalX** [comment]
Поддерживаю оратора выше. В враппер свой добавить обработку таймаута, а вообще таймаут повысить можно прокинув арг куда-нить. В ЯМ точно можно, спотипай доку смотреть надо. Должно быть. 

Первым делом повысить таймаут

**Comment by lemonpaul** [comment]
Количество попыток теперь 5, таймаут можно задать через параметр, по умолчанию - 10.
