### ISSUE TITLE
yandex_music.exceptions.BadRequest

### ISSUE THREAD

**Issue by adeepv** [lemonpaul/yandex2spotify#20]
```
2020-08-08 13:20:54,850 - INFO - Importing playlist Mehdi - Christmass Treasures...
Traceback (most recent call last):
  File "importer.py", line 242, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore, arguments.strict_artists_search).import_all()
  File "importer.py", line 197, in import_all
    item()
  File "importer.py", line 155, in import_playlists
    tracks = self.yandex_client.tracks([track.track_id for track in playlist_tracks if track.album_id]) \
  File "/usr/local/lib/python3.8/dist-packages/yandex_music/client.py", line 34, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yandex_music/client.py", line 1931, in tracks
    return self._get_list('track', track_ids, {'with-positions': with_positions}, timeout, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yandex_music/client.py", line 1868, in _get_list
    result = self._request.post(url, params, timeout=timeout, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yandex_music/utils/request.py", line 260, in post
    result = self._request_wrapper('POST', url, headers=self.headers, proxies=self.proxies, data=data,
  File "/usr/local/lib/python3.8/dist-packages/yandex_music/utils/request.py", line 212, in _request_wrapper
    raise BadRequest(message)
yandex_music.exceptions.BadRequest: {'name': 'validate', 'message': 'Parameters requirements are not met. Errors: [trackIds: Parameter value is not set]; ErrorMessages: []'}

```

**Comment by lemonpaul** [comment]
Could you send playlist link, please?

**Comment by adeepv** [comment]
https://music.yandex.ru/users/adeep/playlists/1032

вс, 9 авг. 2020 г., 15:41 Pavel Lamonov <notifications@github.com>:

**Comment by lemonpaul** [comment]
Is it empty?

**Comment by adeepv** [comment]
No. It contains uploaded music from mp3 files. Yandex prohibit publication
of this files.

пн, 24 авг. 2020 г., 06:37 Pavel Lamonov <notifications@github.com>:

**Comment by lemonpaul** [comment]
Ok, I got it. Import of such tracks are not supported. I will fix it soon.

**Comment by MarshalX** [comment]
Let me know if issues about track with UUIDs (self uploaded) is not gone
