### ISSUE TITLE
Warning message and following crash

### ISSUE THREAD

**Issue by Magorx** [lemonpaul/yandex2spotify#21]
There was a warning asking me to paste this:
2020-11-24 12:54:19,823 - WARNING - Type: <class 'yandex_music.playlist.playlist.Playlist'>; kwargs: {'playlist_uuid': '1663e604-544a-be87-9426-7ca8336ee7fd'}

Not so long after this script crashed. Only 'liked' songs were imported.

**Comment by Magorx** [comment]
The crash message:
Traceback (most recent call last):
  File "importer.py", line 255, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore, arguments.strict_artists_search).import_all()
  File "importer.py", line 208, in import_all
    item()
  File "importer.py", line 165, in import_playlists
    playlist_tracks = playlist.fetch_tracks()
AttributeError: 'Playlist' object has no attribute 'fetch_tracks'

**Comment by MarshalX** [comment]
The problem was about the incorrect version of yandex-music lib
