### ISSUE TITLE
Fails by unknown reason

### ISSUE THREAD

**Issue by kulikov98** [lemonpaul/yandex2spotify#37]
```
2022-11-23 15:13:49,295 - INFO - User ID: 31odwhr4vxksyijcmvq5cojhu52y
Traceback (most recent call last):
  File "/Users/vladimir/Desktop/yandex2spotify/importer.py", line 242, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore, arguments.strict_artists_search).import_all()
  File "/Users/vladimir/Desktop/yandex2spotify/importer.py", line 200, in import_all
    item()
  File "/Users/vladimir/Desktop/yandex2spotify/importer.py", line 130, in import_likes
    likes_tracks = self.yandex_client.users_likes_tracks().tracks
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yandex_music/client.py", line 66, in wrapper
    result = method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yandex_music/client.py", line 2210, in users_likes_tracks
    return self._get_likes(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yandex_music/client.py", line 2178, in _get_likes
    result = self._request.get(url, params, timeout=timeout, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yandex_music/utils/request.py", line 242, in get
    result = self._request_wrapper(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yandex_music/utils/request.py", line 223, in _request_wrapper
    raise NetworkError(f'{message} ({resp.status_code}): {resp.content}')
yandex_music.exceptions.NetworkError: {'name': 'unknown', 'message': 'omitted'}  (500): b'{"invocationInfo":{"req-id":"1669205630130530-213444447781242468","hostname":"music-stable-back-sas-38.sas.yp-c.yandex.net","exec-duration-millis":0},"error":{"name":"unknown","message":"omitted"}}'
```

**Comment by MarshalX** [comment]
Сервер ЯМ пятисотит, жаль это не обработно в этом импротере

**Comment by kulikov98** [comment]
понял, спасибо за ответ 🙂

**Comment by kulikov98** [comment]
UPD: в моём случае проблема была во включенном VPN, без него сработало. Спасибо за скрипт!
