### ISSUE TITLE
Crash after ~100 trackes imported

### ISSUE THREAD

**Issue by nikitades** [lemonpaul/yandex2spotify#39]
**What did I do:**
- obtained all tokens
- managed to launch the script
- waited for like 25 seconds

**What happened:**
The script crashed with the following log:

```
... <some more INFO lines of successful imports> ...
2022-12-09 15:09:12,148 - INFO - Importing track: Husky Rescue - Sound Of Love...
2022-12-09 15:09:12,148 - INFO - Searching "Husky Rescue Sound Of Love"...
2022-12-09 15:09:12,148 - INFO - OK
2022-12-09 15:09:12,242 - INFO - Importing track: Gost, Kriistal Ann - Arise...
2022-12-09 15:09:12,314 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/search returned 400 due to Bad request.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/spotipy/client.py", line 175, in _internal_call
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/search?q=%7B%27id%27%3A+580445%2C+%27error%27%3A+None%2C+%27reason%27%3A+None%2C+%27name%27%3A+%27Gost%27%2C+%27cover%27%3A+%7B%27type%27%3A+%27from-album-cover%27%2C+%27uri%27%3A+%27avatars.yandex.net%2Fget-music-content%2F42108%2F72e8a7e7.a.2527447-1%2F%25%25%27%2C+%27items_uri%27%3A+None%2C+%27dir%27%3A+None%2C+%27version%27%3A+None%2C+%27custom%27%3A+None%2C+%27is_custom%27%3A+None%2C+%27copyright_name%27%3A+None%2C+%27copyright_cline%27%3A+None%2C+%27prefix%27%3A+%2772e8a7e7.a.2527447-1%27%2C+%27error%27%3A+None%7D%2C+%27various%27%3A+False%2C+%27composer%27%3A+False%2C+%27genres%27%3A+%5B%5D%2C+%27og_image%27%3A+None%2C+%27op_image%27%3A+None%2C+%27no_pictures_from_search%27%3A+None%2C+%27counts%27%3A+None%2C+%27available%27%3A+None%2C+%27ratings%27%3A+None%2C+%27links%27%3A+%5B%5D%2C+%27tickets_available%27%3A+None%2C+%27likes_count%27%3A+None%2C+%27popular_tracks%27%3A+%5B%5D%2C+%27regions%27%3A+None%2C+%27decomposed%27%3A+None%2C+%27full_names%27%3A+None%2C+%27hand_made_description%27%3A+None%2C+%27description%27%3A+None%2C+%27countries%27%3A+None%2C+%27en_wikipedia_link%27%3A+None%2C+%27db_aliases%27%3A+None%2C+%27aliases%27%3A+None%2C+%27init_date%27%3A+None%2C+%27end_date%27%3A+None%2C+%27ya_money_id%27%3A+None%7D+Arise&limit=10&offset=0&type=track

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/privet/medved/yandex2spotify/importer.py", line 242, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore, arguments.strict_artists_search).import_all()
  File "/Users/privet/medved/yandex2spotify/importer.py", line 200, in import_all
    item()
  File "/Users/privet/medved/yandex2spotify/importer.py", line 139, in import_likes
    self._add_items_to_spotify(tracks, self.not_imported['Likes'], save_tracks_callback)
  File "/Users/privet/medved/yandex2spotify/importer.py", line 118, in _add_items_to_spotify
    spotify_items.append(self._import_item(item))
  File "/Users/privet/medved/yandex2spotify/importer.py", line 102, in _import_item
    found_items = handle_spotify_exception(self.spotify_client.search)(query, type=type_)[f'{type_}s']['items']
  File "/Users/privet/medved/yandex2spotify/importer.py", line 51, in wrapper
    raise exception
  File "/Users/privet/medved/yandex2spotify/importer.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/spotipy/client.py", line 463, in search
    return self._get(
  File "/opt/homebrew/lib/python3.10/site-packages/spotipy/client.py", line 210, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/spotipy/client.py", line 186, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/search?q=%7B%27id%27%3A+580445%2C+%27error%27%3A+None%2C+%27reason%27%3A+None%2C+%27name%27%3A+%27Gost%27%2C+%27cover%27%3A+%7B%27type%27%3A+%27from-album-cover%27%2C+%27uri%27%3A+%27avatars.yandex.net%2Fget-music-content%2F42108%2F72e8a7e7.a.2527447-1%2F%25%25%27%2C+%27items_uri%27%3A+None%2C+%27dir%27%3A+None%2C+%27version%27%3A+None%2C+%27custom%27%3A+None%2C+%27is_custom%27%3A+None%2C+%27copyright_name%27%3A+None%2C+%27copyright_cline%27%3A+None%2C+%27prefix%27%3A+%2772e8a7e7.a.2527447-1%27%2C+%27error%27%3A+None%7D%2C+%27various%27%3A+False%2C+%27composer%27%3A+False%2C+%27genres%27%3A+%5B%5D%2C+%27og_image%27%3A+None%2C+%27op_image%27%3A+None%2C+%27no_pictures_from_search%27%3A+None%2C+%27counts%27%3A+None%2C+%27available%27%3A+None%2C+%27ratings%27%3A+None%2C+%27links%27%3A+%5B%5D%2C+%27tickets_available%27%3A+None%2C+%27likes_count%27%3A+None%2C+%27popular_tracks%27%3A+%5B%5D%2C+%27regions%27%3A+None%2C+%27decomposed%27%3A+None%2C+%27full_names%27%3A+None%2C+%27hand_made_description%27%3A+None%2C+%27description%27%3A+None%2C+%27countries%27%3A+None%2C+%27en_wikipedia_link%27%3A+None%2C+%27db_aliases%27%3A+None%2C+%27aliases%27%3A+None%2C+%27init_date%27%3A+None%2C+%27end_date%27%3A+None%2C+%27ya_money_id%27%3A+None%7D+Arise&limit=10&offset=0&type=track:
 Bad request.
```

**Comment by MarshalX** [comment]
@lemonpaul it looks like the bug. In:

https://github.com/lemonpaul/yandex2spotify/blob/b508c191229c438c95b4b3e4e3f1bfcc04bd8dcc/importer.py#L101

`item.artists[0]` return `__str__`... should be something like `item.artists[0].name` instead

tbh there is should be join like here:
https://github.com/lemonpaul/yandex2spotify/blob/b508c191229c438c95b4b3e4e3f1bfcc04bd8dcc/importer.py#L94-L95

**Comment by MarshalX** [comment]
@glebliutsko cc

**Comment by MarshalX** [comment]
@nikitades you can try to replace 101st line 

from 
```python
query = f'{item.artists[0]} {item.title}' 
```

to
```python
query = f'{item.artists[0].name} {item.title}' 
```

as a workaround
