### ISSUE TITLE
Spotify API limit exceeded

### ISSUE THREAD

**Issue by thegalkin** [lemonpaul/yandex2spotify#4]
Достиг лимита обращений.

1. Когда можно будет продолжить? 
2. Запускать ли скрипт заново?(достигнет лимита на том же месте по трекам, ничего нового не загрузив).
3. Не хватает менее пугающей обертки ошибки...

`INFO - Saving 50 tracks in playlist iPhone...
2020-07-16 14:03:25,201 - ERROR - HTTP Error for POST to {ссылка на апи, удалил} returned 429 due to API rate limit exceeded
Traceback (most recent call last):
  File "/Users/thegalkin/GitHub/yandex2spotify/env/lib/python3.8/site-packages/spotipy/client.py", line 175, in _internal_call
    response.raise_for_status()
  File "/Users/thegalkin/GitHub/yandex2spotify/env/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: unknown for url: {ссылка на апи, удалил}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 132, in <module>
    Importer(spotify_client_, yandex_client_).import_all()
  File "main.py", line 92, in import_all
    self.import_playlists()
  File "main.py", line 88, in import_playlists
    self._add_music_to_spotify(tracks, self.not_imported_tracks[playlist.title], save_tracks_callback)
  File "main.py", line 54, in _add_music_to_spotify
    save_tracks_callback(self, chunk)
  File "main.py", line 85, in save_tracks_callback
    importer.spotify_client.user_playlist_add_tracks(importer.user, spotify_playlist_id, spotify_tracks)
  File "/Users/thegalkin/GitHub/yandex2spotify/env/lib/python3.8/site-packages/spotipy/client.py", line 687, in user_playlist_add_tracks
    return self._post(
  File "/Users/thegalkin/GitHub/yandex2spotify/env/lib/python3.8/site-packages/spotipy/client.py", line 215, in _post
    return self._internal_call("POST", url, payload, kwargs)
  File "/Users/thegalkin/GitHub/yandex2spotify/env/lib/python3.8/site-packages/spotipy/client.py", line 186, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 429, code:-1 - {ссылка на апи, удалил}
 API rate limit exceeded`

**Comment by thegalkin** [comment]
По итогу, не добавились треки в спотифай.

**Comment by thegalkin** [comment]
Поправка, плейлисты вроде добавились

**Comment by lemonpaul** [comment]
А на какой скорости соединения это исключение вылетает?

**Comment by thegalkin** [comment]
Не знаю, но подключено 500мбит по Ethernet.

**Comment by lemonpaul** [comment]
Попробуй ветку spotify-api-limit: https://github.com/lemonpaul/yandex2spotify/tree/spotify-api-limit
