### ISSUE TITLE
Fails with "latin-1' codec can't encode character '\u2014' in position 47: ordinal not in range(256)"

### ISSUE THREAD

**Issue by SButterfly** [lemonpaul/yandex2spotify#40]
```
Yandex Music API v2.0.1, Copyright (C) 2019-2022 Il`ya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3)

Traceback (most recent call last):
  File "/Users/sermakov/IdeaProjects/yandex2spotify/importer.py", line 241, in <module>
    yandex_client_.init()
  File "/opt/homebrew/lib/python3.10/site-packages/yandex_music/client.py", line 66, in wrapper
    result = method(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/yandex_music/client.py", line 152, in init
    self.me = self.account_status()
  File "/opt/homebrew/lib/python3.10/site-packages/yandex_music/client.py", line 66, in wrapper
    result = method(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/yandex_music/client.py", line 173, in account_status
    result = self._request.get(url, timeout=timeout, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/yandex_music/utils/request.py", line 242, in get
    result = self._request_wrapper(
  File "/opt/homebrew/lib/python3.10/site-packages/yandex_music/utils/request.py", line 196, in _request_wrapper
    resp = requests.request(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1255, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2014' in position 47: ordinal not in range(256)
```

**Comment by SButterfly** [comment]
Somehow double dash `--` from the Yandex token has transformed into the long dash `—`.

**Comment by MarshalX** [comment]
> Somehow double dash `--` from the Yandex token has transformed into the long dash `—`.

welcome to macos world ;d
